#!/usr/bin/env bash
ssh_hostconfig_root="azog-quetzal"
backup_dir="/run/media/quetzal/Backup"
includelist="rsync_includelist"
excludelist="rsync_excludelist"
dryrun_opts="--dry-run"
if [ $# -eq 1 ]; then
    if [ "$1" != "realrun" ]; then
        echo "Unknown parameter!"
        echo "Usage: $0 [<realrun>]"
        exit 1
    fi
    dryrun_opts=""
fi
backup_id=`hostname --fqdn`
if ( sudo ssh $ssh_hostconfig_root "[ ! -d ${backup_dir} ]" ); then
    echo "Backup directory doesn't exist!"
    exit 1
fi
source_dir="${backup_dir}/${backup_id}"
if ( sudo ssh $ssh_hostconfig_root "[ ! -d ${source_dir} ]" ); then
    echo "Source directory doesn't exist!"
    exit 1
fi
generic_opts="--archive --no-owner --no-group --verbose --progress --human-readable"
deletes_opts=""
filelist_opts="--exclude-from=${excludelist} --include-from=${includelist}"
source_def="${ssh_hostconfig_root}:${source_dir}/."
destination_def="/."
sudo rsync $dryrun_opts $generic_opts $deletes_opts $filelist_opts $source_def $destination_def
if [ "$1" == "realrun" ]; then
    ./rsync_setperms
fi

